"""Curated calamansi sources reviewed on 2026-09-08; summaries are original."""
CATEGORIES = [('all', 'All'), ('basics', 'Calamansi Basics'), ('growing', 'Farming & Growing'), ('harvest', 'Harvest & Handling'), ('research', 'Research & Industry')]
INTRODUCTION_URL = 'https://ati2.da.gov.ph/ati-4b/content/sites/default/files/2022-12/calamansi_final.pdf'
INTRODUCTION_SOURCE = 'DA Agricultural Training Institute'
ARTICLES = [
    {'title': 'Getting to Know Calamansi', 'category': 'basics', 'summary': 'Meet the small citrus tree widely grown in Philippine backyards. This DA guide introduces its fruit, growing requirements, and uses in drinks and food.', 'source': 'DA Agricultural Training Institute · Guide (PDF)', 'url': INTRODUCTION_URL, 'image': 'images/samples/green.jpg', 'image_alt': 'Green calamansi fruits'},
    {'title': 'How Can You Use Calamansi?', 'category': 'basics', 'summary': 'Calamondin has tart juice used in sauces, beverages, baked goods, and marmalade. This university article also discusses container growing in a Florida gardening context.', 'source': 'University of Florida IFAS · 2017', 'url': 'https://blogs.ifas.ufl.edu/nassauco/2017/06/11/q-calamondin-citrus-tree-yard-no-idea-fruit-since-sour-eat/', 'image': 'images/samples/mixed.jpg', 'image_alt': 'Green and yellow calamansi fruits'},
    {'title': 'Growing Calamansi: Production Guide', 'category': 'growing', 'summary': 'Learn about planting materials, soil, spacing, and orchard care. The guide highlights the importance of avoiding waterlogged sites when growing calamansi.', 'source': 'DA Agricultural Training Institute · Guide (PDF)', 'url': INTRODUCTION_URL + '#page=4', 'image': 'images/samples/batch.jpg', 'image_alt': 'A basket of harvested calamansi'},
    {'title': 'Harvesting Calamansi with Care', 'category': 'harvest', 'summary': 'The DA guide recommends careful picking, keeping part of the stem attached, and protecting the skin from injury during harvest. Open the harvesting section to learn more.', 'source': 'DA Agricultural Training Institute · Harvesting (PDF)', 'url': INTRODUCTION_URL + '#page=11', 'image': 'images/samples/green.jpg', 'image_alt': 'Fresh green calamansi'},
    {'title': 'Sustainable Calamansi Farming in Nueva Ecija', 'category': 'growing', 'summary': 'A 2024 DOST-PCAARRD and NVSU training addressed planting materials, orchard spacing, and citrus rind borer management with calamansi farmers in Nueva Ecija.', 'source': 'DOST-PCAARRD · March 14, 2024', 'url': 'https://www.pcaarrd.dost.gov.ph/index.php/quick-information-dispatch-qid-articles/dost-pcaarrd-nvsu-spearhead-calamansi-training-on-standard-and-sustainable-cultural-management-in-nueva-ecija', 'image': 'images/samples/batch.jpg', 'image_alt': 'Harvested calamansi fruits'},
    {'title': 'Calamansi Production and Processing Innovations', 'category': 'research', 'summary': 'Read about a farmer learning visit to NVSU citrus facilities. The activity explored production and processing practices, including hands-on calamansi grafting and budding.', 'source': 'DOST-PCAARRD · August 9, 2024', 'url': 'https://www.pcaarrd.dost.gov.ph/index.php/quick-information-dispatch-qid-articles/dost-pcaarrd-agri-aqua-business-hub-brings-calamansi-farmers-to-nvsu-for-benchmarking', 'image': 'images/samples/mixed.jpg', 'image_alt': 'Calamansi in different colors'},
]

def find_articles(query='', category='all'):
    terms = query.casefold().split()
    return [dict(article, category_label=dict(CATEGORIES)[article['category']]) for article in ARTICLES
            if (category == 'all' or article['category'] == category)
            and all(term in ' '.join([article['title'], article['summary'], article['source'], dict(CATEGORIES)[article['category']]]).casefold() for term in terms)]
