# Generated by Django 6.1 on 2026-09-02 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('grade_letter', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('fruit_count_total', models.IntegerField(default=0)),
                ('fruit_count_good', models.IntegerField(default=0)),
                ('fruit_count_defective', models.IntegerField(default=0)),
                ('size_small_pct', models.FloatField(default=0.0)),
                ('size_medium_pct', models.FloatField(default=0.0)),
                ('size_large_pct', models.FloatField(default=0.0)),
                ('size_xl_pct', models.FloatField(default=0.0)),
                ('ripeness_unripe_pct', models.FloatField(default=0.0)),
                ('ripeness_overripe_pct', models.FloatField(default=0.0)),
                ('ripeness_ripe_pct', models.FloatField(default=0.0)),
                ('defect_blemished_pct', models.FloatField(default=0.0)),
                ('defect_mold_pct', models.FloatField(default=0.0)),
                ('defect_cracked_pct', models.FloatField(default=0.0)),
                ('defect_insect_pct', models.FloatField(default=0.0)),
                ('defect_bruised_pct', models.FloatField(default=0.0)),
                ('defect_foreign_matter_pct', models.FloatField(default=0.0)),
                ('model_version', models.CharField(default='mock-v0', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='scans/')),
                ('mock_annotations', models.JSONField(blank=True, default=list)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='analyzer.scan')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='training/')),
                ('label', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
