# Generated by Django 6.1.1 on 2026-09-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='grade_letter',
        ),
        migrations.AddField(
            model_name='scan',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('Best Quality', 'Best Quality'), ('Good Quality', 'Good Quality'), ('Average', 'Average'), ('Rejected', 'Rejected')], max_length=50, null=True),
        ),
    ]
